- name: check roboshop user exists or not
  ansible.builtin.command: id roboshop 
  register: output
  ignore_errors: true

- name: create user roboshop
  ansible.builtin.user:
    name: roboshop
  when: output.rc != 0

- name: check /app directory exists or not
  ansible.builtin.stat:
    path: /app
  register: directory

- name: create directory
  ansible.builtin.file:
    path: /app
    state: directory
  when: directory.stat.exists == False

# - name: "download {{component}} artifact"
#   ansible.builtin.get_url:
#     url: "https://roboshop-builds.s3.amazonaws.com/{{component}}.zip"
#     dest: /tmp

- name: "download artifact from nexus and unarchive"
  ansible.builtin.unarchive:
    src: "{{nexus_url}}/{{component}}/{{group_id}}/{{component}}/{{app_version}}/{{component}}-{{app_version}}.zip"
    dest: /app
    remote_src: yes