- name: lookup ssm parameter store in specified region
  debug: msg="{{ lookup('amazon.aws.aws_ssm', 'hello', region='us-east-1' ) }}"

- name: copy systemd template
  ansible.builtin.template:
    src: "{{component}}.service"
    dest: /etc/systemd/system/{{component}}.service

- name: daemon-reload
  ansible.builtin.systemd:
    daemon-reload: yes
    
- name: restart {{component}}
  ansible.builtin.service:
    state: restarted
    name: "{{component}}"
    enabled: yes