- name: copy {{component}} service
  ansible.builtin.copy:
    src: "{{component}}.service"
    dest: /etc/systemd/system/{{component}}.service

- name: daemon-reload
  ansible.builtin.systemd:
    daemon-reload: yes
    
- name: restart {{component}}
  ansible.builtin.service:
    state: restarted
    name: "{{component}}"
    enabled: yes